name: Dependency Review

on:
  pull_request_target:

jobs:
  dependency-review:
    uses: nlobby4/.github/workflows/dependency-review.yml@main
    permissions:
      contents: read
      pull-requests: write
